### ISSUE TITLE
code-highlighter doesn't work with ant-design form

### ISSUE THREAD

**Issue by sukechris** [margox/braft-extensions#11]

**Comment by margox** [comment]
show me your code plz.

**Comment by margox** [comment]
```js
BraftEditor.use(
  CodeHighlighter({
    //includeEditors: ["editor-with-code-highlighter"]
  })
);
```
seems like the `includeEditors` not working in Ant Design Form, you can just comment it out, and I will try to solve this in next version of braft editor.

**Comment by margox** [comment]
The reason for this problem is because the id attribute of the BraftEditor component is overwritten by the first parameter of the getFieldDecorator method. In the 2.2.4 version of the draft-editor, I added a new attribute editorId, which is exactly the same as the id attribute but won't be overwritten by getFieldDecorator, so you can use like this:
```jsx
BraftEditor.use(
  CodeHighlighter({
    //includeEditors: ["editor-with-code-highlighter"]
  })
);

<BraftEditor editorId="editor-with-code-highlighter" />
```

**Comment by sukechris** [comment]
@margox it's great! :thumbsup: :thumbsup: :thumbsup: thank you for your attention.

**Comment by fenglijunnb** [comment]
@sukechris 你好，请问一下你有没有用过https://www.yuque.com/braft-editor/be/mrgy92  这个清空编辑器的功能，我给他放到form里方法就不管用了
